name: Angular Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  angular:
    name: Angular Build
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
      options: >
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3

    strategy:
      matrix:
        node-version: [20.14]

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.14
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install backend dependencies
        run: npm install
        working-directory: app-backend

      - name: Start Backend Server
        env:
          MONGO_URI: "mongodb://localhost:27017/sample"
        run: node backend.js &
        working-directory: app-backend

      - name: Wait for Backend to Start
        run: sleep 10

      - name: Install frontend dependencies
        run: npm ci
        working-directory: app-frontend

      - name: Run frontend tests
        run: npm run test:ci
        working-directory: app-frontend

      - name: Build frontend
        run: npm run build
        working-directory: app-frontend
