
name: Angular Build

# {1}
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  angular:
    name: Angular Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.14]
        
    steps:
      # {2}
      - name: Checkout the source code
        uses: actions/checkout@v4

      # {3}
      - name: Install Angular CLI globally
        run: npm install -g @angular/cli

      # {4}
      - name: Setup Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 20.14
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # {5}
      - name: Install dependencies
        run: npm ci
        working-directory: app-frontend
      # {6}
      - name: Run tests
        run: npm run test:ci
        working-directory: app-frontend
      # {7}
      - name: Build
        run: npm run build
        working-directory: app-frontend
